version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "cotion"
      POSTGRES_USER: "user"
      POSTGRES_HOST: "localhost"
      POSTGRES_PASSWORD: "love"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/insert_tables.sql:/docker-entrypoint-initdb.d/insert_tables.sql
    ports:
      - "5432:5432"
    restart: unless-stopped