version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "cotion"
      POSTGRES_USER: "user"
      POSTGRES_HOST: "localhost"
      POSTGRES_PASSWORD: "love"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/insert_tables.sql:/docker-entrypoint-initdb.d/insert_tables.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ozontech
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage:
