#build stage
FROM golang:1.17-buster AS builder
WORKDIR /session
ADD . .
ENV CGO_ENABLED=0
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go build ./cmd/grpcSession.go

#run stage
FROM alpine:latest
RUN apk upgrade --update-cache --available && \
    rm -rf /var/cache/apk/*

WORKDIR /session

COPY --from=builder /session/ .
ADD cmd .

EXPOSE 5001

CMD ["./grpcSession"]