// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: internal/note/domain/note.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Note struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Body string `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *Note) Reset() {
	*x = Note{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_note_domain_note_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_internal_note_domain_note_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_internal_note_domain_note_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Note) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Note) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NoteID string `protobuf:"bytes,2,opt,name=noteID,proto3" json:"noteID,omitempty"`
	Note   *Note  `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *NoteReq) Reset() {
	*x = NoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_note_domain_note_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteReq) ProtoMessage() {}

func (x *NoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_note_domain_note_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteReq.ProtoReflect.Descriptor instead.
func (*NoteReq) Descriptor() ([]byte, []int) {
	return file_internal_note_domain_note_proto_rawDescGZIP(), []int{1}
}

func (x *NoteReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *NoteReq) GetNoteID() string {
	if x != nil {
		return x.NoteID
	}
	return ""
}

func (x *NoteReq) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type Nothing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_note_domain_note_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_internal_note_domain_note_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_internal_note_domain_note_proto_rawDescGZIP(), []int{2}
}

func (x *Nothing) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_internal_note_domain_note_proto protoreflect.FileDescriptor

var file_internal_note_domain_note_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x04, 0x4e,
	0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x5d, 0x0a, 0x07, 0x4e,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x74, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x2e,
	0x4e, 0x6f, 0x74, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x21, 0x0a, 0x07, 0x4e, 0x6f,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x81, 0x02,
	0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a,
	0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65,
	0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e,
	0x6f, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x2a, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x2e,
	0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f,
	0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x2e, 0x4e,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74,
	0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65,
	0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x4e,
	0x6f, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x32, 0x0a,
	0x09, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x4e, 0x6f, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6e, 0x6f,
	0x74, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_note_domain_note_proto_rawDescOnce sync.Once
	file_internal_note_domain_note_proto_rawDescData = file_internal_note_domain_note_proto_rawDesc
)

func file_internal_note_domain_note_proto_rawDescGZIP() []byte {
	file_internal_note_domain_note_proto_rawDescOnce.Do(func() {
		file_internal_note_domain_note_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_note_domain_note_proto_rawDescData)
	})
	return file_internal_note_domain_note_proto_rawDescData
}

var file_internal_note_domain_note_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_note_domain_note_proto_goTypes = []interface{}{
	(*Note)(nil),    // 0: grpcNote.Note
	(*NoteReq)(nil), // 1: grpcNote.NoteReq
	(*Nothing)(nil), // 2: grpcNote.Nothing
}
var file_internal_note_domain_note_proto_depIdxs = []int32{
	0, // 0: grpcNote.NoteReq.note:type_name -> grpcNote.Note
	1, // 1: grpcNote.NoteService.Save:input_type -> grpcNote.NoteReq
	1, // 2: grpcNote.NoteService.Get:input_type -> grpcNote.NoteReq
	1, // 3: grpcNote.NoteService.Update:input_type -> grpcNote.NoteReq
	1, // 4: grpcNote.NoteService.Delete:input_type -> grpcNote.NoteReq
	1, // 5: grpcNote.NoteService.NotesList:input_type -> grpcNote.NoteReq
	2, // 6: grpcNote.NoteService.Save:output_type -> grpcNote.Nothing
	0, // 7: grpcNote.NoteService.Get:output_type -> grpcNote.Note
	2, // 8: grpcNote.NoteService.Update:output_type -> grpcNote.Nothing
	2, // 9: grpcNote.NoteService.Delete:output_type -> grpcNote.Nothing
	0, // 10: grpcNote.NoteService.NotesList:output_type -> grpcNote.Note
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_note_domain_note_proto_init() }
func file_internal_note_domain_note_proto_init() {
	if File_internal_note_domain_note_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_note_domain_note_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Note); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_note_domain_note_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_note_domain_note_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nothing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_note_domain_note_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_note_domain_note_proto_goTypes,
		DependencyIndexes: file_internal_note_domain_note_proto_depIdxs,
		MessageInfos:      file_internal_note_domain_note_proto_msgTypes,
	}.Build()
	File_internal_note_domain_note_proto = out.File
	file_internal_note_domain_note_proto_rawDesc = nil
	file_internal_note_domain_note_proto_goTypes = nil
	file_internal_note_domain_note_proto_depIdxs = nil
}
